// This file is auto-generated by @hey-api/openapi-ts

export type Volo_Abp_Account_ChangePasswordInput = {
    currentPassword?: (string) | null;
    newPassword: string;
};

export type Volo_Abp_Account_ProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    isExternal?: boolean;
    hasPassword?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_RegisterDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    emailAddress: string;
    password: string;
    appName: string;
};

export type Volo_Abp_Account_ResetPasswordDto = {
    userId?: string;
    resetToken: string;
    password: string;
};

export type Volo_Abp_Account_SendPasswordResetCodeDto = {
    email: string;
    appName: string;
    returnUrl?: (string) | null;
    returnUrlHash?: (string) | null;
};

export type Volo_Abp_Account_UpdateProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_VerifyPasswordResetTokenInput = {
    userId?: string;
    resetToken: string;
};

export type Volo_Abp_Application_Dtos_ListResultDto_1__Volo_Abp_Identity_IdentityRoleDto__Volo_Abp_Identity_Application_Contracts__Version_8_3_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
};

export type Volo_Abp_Application_Dtos_ListResultDto_1__Volo_Abp_Users_UserData__Volo_Abp_Users_Abstractions__Version_8_3_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Users_UserData> | null;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_Identity_IdentityRoleDto__Volo_Abp_Identity_Application_Contracts__Version_8_3_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_Identity_IdentityUserDto__Volo_Abp_Identity_Application_Contracts__Version_8_3_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityUserDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_TenantManagement_TenantDto__Volo_Abp_TenantManagement_Application_Contracts__Version_8_3_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_TenantManagement_TenantDto> | null;
    totalCount?: number;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto = {
    success?: boolean;
    tenantId?: (string) | null;
    name?: (string) | null;
    normalizedName?: (string) | null;
    isActive?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_FeatureManagement_FeatureDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    value?: (string) | null;
    provider?: Volo_Abp_FeatureManagement_FeatureProviderDto;
    description?: (string) | null;
    valueType?: Volo_Abp_Validation_StringValues_IStringValueType;
    depth?: number;
    parentName?: (string) | null;
};

export type Volo_Abp_FeatureManagement_FeatureGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    features?: Array<Volo_Abp_FeatureManagement_FeatureDto> | null;
};

export type Volo_Abp_FeatureManagement_FeatureProviderDto = {
    name?: (string) | null;
    key?: (string) | null;
};

export type Volo_Abp_FeatureManagement_GetFeatureListResultDto = {
    groups?: Array<Volo_Abp_FeatureManagement_FeatureGroupDto> | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeatureDto = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeaturesDto = {
    features?: Array<Volo_Abp_FeatureManagement_UpdateFeatureDto> | null;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Identity_IdentityRoleCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
};

export type Volo_Abp_Identity_IdentityRoleDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    isDefault?: boolean;
    isStatic?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityRoleUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password: string;
};

export type Volo_Abp_Identity_IdentityUserDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    lockoutEnd?: (string) | null;
    concurrencyStamp?: (string) | null;
    entityVersion?: number;
    lastPasswordChangeTime?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateRolesDto = {
    roleNames: Array<(string)>;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_PermissionManagement_GetPermissionListResultDto = {
    entityDisplayName?: (string) | null;
    groups?: Array<Volo_Abp_PermissionManagement_PermissionGroupDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGrantInfoDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    parentName?: (string) | null;
    isGranted?: boolean;
    allowedProviders?: Array<(string)> | null;
    grantedProviders?: Array<Volo_Abp_PermissionManagement_ProviderInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    displayNameKey?: (string) | null;
    displayNameResource?: (string) | null;
    permissions?: Array<Volo_Abp_PermissionManagement_PermissionGrantInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_ProviderInfoDto = {
    providerName?: (string) | null;
    providerKey?: (string) | null;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionDto = {
    name?: (string) | null;
    isGranted?: boolean;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionsDto = {
    permissions?: Array<Volo_Abp_PermissionManagement_UpdatePermissionDto> | null;
};

export type Volo_Abp_SettingManagement_EmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress?: (string) | null;
    defaultFromDisplayName?: (string) | null;
};

export type Volo_Abp_SettingManagement_SendTestEmailInput = {
    senderEmailAddress: string;
    targetEmailAddress: string;
    subject: string;
    body?: (string) | null;
};

export type Volo_Abp_SettingManagement_UpdateEmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress: string;
    defaultFromDisplayName: string;
};

export type Volo_Abp_TenantManagement_TenantCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    adminEmailAddress: string;
    adminPassword: string;
};

export type Volo_Abp_TenantManagement_TenantDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_TenantManagement_TenantUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Users_UserData = {
    id?: string;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    isActive?: boolean;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_Validation_StringValues_IStringValueType = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
    validator?: Volo_Abp_Validation_StringValues_IValueValidator;
};

export type Volo_Abp_Validation_StringValues_IValueValidator = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
};

export type GetApiAbpApiDefinitionData = {
    query?: {
        IncludeTypes?: boolean;
    };
};

export type GetApiAbpApiDefinitionResponse = (Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel);

export type GetApiAbpApiDefinitionError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpApplicationConfigurationData = {
    query?: {
        IncludeLocalizationResources?: boolean;
    };
};

export type GetApiAbpApplicationConfigurationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto);

export type GetApiAbpApplicationConfigurationError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpApplicationLocalizationData = {
    query: {
        CultureName: string;
        OnlyDynamics?: boolean;
    };
};

export type GetApiAbpApplicationLocalizationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto);

export type GetApiAbpApplicationLocalizationError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpMultiTenancyTenantsByNameByNameData = {
    path: {
        name: string;
    };
};

export type GetApiAbpMultiTenancyTenantsByNameByNameResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByNameByNameError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAbpMultiTenancyTenantsByIdByIdData = {
    path: {
        id: string;
    };
};

export type GetApiAbpMultiTenancyTenantsByIdByIdResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByIdByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountRegisterData = {
    body?: Volo_Abp_Account_RegisterDto;
};

export type PostApiAccountRegisterResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PostApiAccountRegisterError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountSendPasswordResetCodeData = {
    body?: Volo_Abp_Account_SendPasswordResetCodeDto;
};

export type PostApiAccountSendPasswordResetCodeResponse = (unknown);

export type PostApiAccountSendPasswordResetCodeError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountVerifyPasswordResetTokenData = {
    body?: Volo_Abp_Account_VerifyPasswordResetTokenInput;
};

export type PostApiAccountVerifyPasswordResetTokenResponse = (boolean);

export type PostApiAccountVerifyPasswordResetTokenError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountResetPasswordData = {
    body?: Volo_Abp_Account_ResetPasswordDto;
};

export type PostApiAccountResetPasswordResponse = (unknown);

export type PostApiAccountResetPasswordError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountDynamicClaimsRefreshResponse = (unknown);

export type PostApiAccountDynamicClaimsRefreshError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiSettingManagementEmailingResponse = (Volo_Abp_SettingManagement_EmailSettingsDto);

export type GetApiSettingManagementEmailingError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiSettingManagementEmailingData = {
    body?: Volo_Abp_SettingManagement_UpdateEmailSettingsDto;
};

export type PostApiSettingManagementEmailingResponse = (unknown);

export type PostApiSettingManagementEmailingError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiSettingManagementEmailingSendTestEmailData = {
    body?: Volo_Abp_SettingManagement_SendTestEmailInput;
};

export type PostApiSettingManagementEmailingSendTestEmailResponse = (unknown);

export type PostApiSettingManagementEmailingSendTestEmailError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiFeatureManagementFeaturesData = {
    query?: {
        providerKey?: string;
        providerName?: string;
    };
};

export type GetApiFeatureManagementFeaturesResponse = (Volo_Abp_FeatureManagement_GetFeatureListResultDto);

export type GetApiFeatureManagementFeaturesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiFeatureManagementFeaturesData = {
    body?: Volo_Abp_FeatureManagement_UpdateFeaturesDto;
    query?: {
        providerKey?: string;
        providerName?: string;
    };
};

export type PutApiFeatureManagementFeaturesResponse = (unknown);

export type PutApiFeatureManagementFeaturesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiFeatureManagementFeaturesData = {
    query?: {
        providerKey?: string;
        providerName?: string;
    };
};

export type DeleteApiFeatureManagementFeaturesResponse = (unknown);

export type DeleteApiFeatureManagementFeaturesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiPermissionManagementPermissionsData = {
    query?: {
        providerKey?: string;
        providerName?: string;
    };
};

export type GetApiPermissionManagementPermissionsResponse = (Volo_Abp_PermissionManagement_GetPermissionListResultDto);

export type GetApiPermissionManagementPermissionsError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiPermissionManagementPermissionsData = {
    body?: Volo_Abp_PermissionManagement_UpdatePermissionsDto;
    query?: {
        providerKey?: string;
        providerName?: string;
    };
};

export type PutApiPermissionManagementPermissionsResponse = (unknown);

export type PutApiPermissionManagementPermissionsError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type GetApiAccountMyProfileError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiAccountMyProfileData = {
    body?: Volo_Abp_Account_UpdateProfileDto;
};

export type PutApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type PutApiAccountMyProfileError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAccountMyProfileChangePasswordData = {
    body?: Volo_Abp_Account_ChangePasswordInput;
};

export type PostApiAccountMyProfileChangePasswordResponse = (unknown);

export type PostApiAccountMyProfileChangePasswordError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityRolesAllResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityRolesAllError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityRolesData = {
    query?: {
        ExtraProperties?: {
            [key: string]: unknown;
        };
        Filter?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiIdentityRolesResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiIdentityRolesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiIdentityRolesData = {
    body?: Volo_Abp_Identity_IdentityRoleCreateDto;
};

export type PostApiIdentityRolesResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type PostApiIdentityRolesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityRolesByIdData = {
    path: {
        id: string;
    };
};

export type GetApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type GetApiIdentityRolesByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiIdentityRolesByIdData = {
    body?: Volo_Abp_Identity_IdentityRoleUpdateDto;
    path: {
        id: string;
    };
};

export type PutApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type PutApiIdentityRolesByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiIdentityRolesByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiIdentityRolesByIdResponse = (unknown);

export type DeleteApiIdentityRolesByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiMultiTenancyTenantsByIdData = {
    path: {
        id: string;
    };
};

export type GetApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type GetApiMultiTenancyTenantsByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiMultiTenancyTenantsByIdData = {
    body?: Volo_Abp_TenantManagement_TenantUpdateDto;
    path: {
        id: string;
    };
};

export type PutApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type PutApiMultiTenancyTenantsByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiMultiTenancyTenantsByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiMultiTenancyTenantsByIdResponse = (unknown);

export type DeleteApiMultiTenancyTenantsByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiMultiTenancyTenantsData = {
    query?: {
        Filter?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiMultiTenancyTenantsResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiMultiTenancyTenantsError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiMultiTenancyTenantsData = {
    body?: Volo_Abp_TenantManagement_TenantCreateDto;
};

export type PostApiMultiTenancyTenantsResponse = (Volo_Abp_TenantManagement_TenantDto);

export type PostApiMultiTenancyTenantsError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    path: {
        id: string;
    };
};

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (string);

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    path: {
        id: string;
    };
    query?: {
        defaultConnectionString?: string;
    };
};

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    path: {
        id: string;
    };
};

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiAppTestUserIdResponse = (string);

export type GetApiAppTestUserIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiAppTestWithErrorData = {
    query?: {
        username?: string;
    };
};

export type PostApiAppTestWithErrorResponse = (string);

export type PostApiAppTestWithErrorError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiSettingManagementTimezoneResponse = (string);

export type GetApiSettingManagementTimezoneError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiSettingManagementTimezoneData = {
    query?: {
        timezone?: string;
    };
};

export type PostApiSettingManagementTimezoneResponse = (unknown);

export type PostApiSettingManagementTimezoneError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiSettingManagementTimezoneTimezonesResponse = (Array<Volo_Abp_NameValue>);

export type GetApiSettingManagementTimezoneTimezonesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersByIdData = {
    path: {
        id: string;
    };
};

export type GetApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiIdentityUsersByIdData = {
    body?: Volo_Abp_Identity_IdentityUserUpdateDto;
    path: {
        id: string;
    };
};

export type PutApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PutApiIdentityUsersByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type DeleteApiIdentityUsersByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiIdentityUsersByIdResponse = (unknown);

export type DeleteApiIdentityUsersByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersData = {
    query?: {
        ExtraProperties?: {
            [key: string]: unknown;
        };
        Filter?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiIdentityUsersResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiIdentityUsersError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PostApiIdentityUsersData = {
    body?: Volo_Abp_Identity_IdentityUserCreateDto;
};

export type PostApiIdentityUsersResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PostApiIdentityUsersError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersByIdRolesData = {
    path: {
        id: string;
    };
};

export type GetApiIdentityUsersByIdRolesResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityUsersByIdRolesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type PutApiIdentityUsersByIdRolesData = {
    body?: Volo_Abp_Identity_IdentityUserUpdateRolesDto;
    path: {
        id: string;
    };
};

export type PutApiIdentityUsersByIdRolesResponse = (unknown);

export type PutApiIdentityUsersByIdRolesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersAssignableRolesResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityUsersAssignableRolesError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersByUsernameByUserNameData = {
    path: {
        userName: string;
    };
};

export type GetApiIdentityUsersByUsernameByUserNameResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByUsernameByUserNameError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersByEmailByEmailData = {
    path: {
        email: string;
    };
};

export type GetApiIdentityUsersByEmailByEmailResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByEmailByEmailError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersLookupByIdData = {
    path: {
        id: string;
    };
};

export type GetApiIdentityUsersLookupByIdResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupByIdError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersLookupByUsernameByUserNameData = {
    path: {
        userName: string;
    };
};

export type GetApiIdentityUsersLookupByUsernameByUserNameResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupByUsernameByUserNameError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersLookupSearchData = {
    query?: {
        ExtraProperties?: {
            [key: string]: unknown;
        };
        Filter?: string;
        MaxResultCount?: number;
        SkipCount?: number;
        Sorting?: string;
    };
};

export type GetApiIdentityUsersLookupSearchResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityUsersLookupSearchError = (Volo_Abp_Http_RemoteServiceErrorResponse);

export type GetApiIdentityUsersLookupCountData = {
    query?: {
        Filter?: string;
    };
};

export type GetApiIdentityUsersLookupCountResponse = (number);

export type GetApiIdentityUsersLookupCountError = (Volo_Abp_Http_RemoteServiceErrorResponse);